name: Chris J Rodriguez
favicon: null
layout_spectrum: 0.41142786270938814
typography_spectrum: 0.05366878304630518
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7382104976568371
  lightness: 0.23412063159048557
  saturation: 0.2002002657391131
  rhythmicContrast: 0.23423607810400426
purpose: []
